// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nowfrwpknymkzujijgsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vd2Zyd3Brbnlta3p1amlqZ3N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MzgxNDQsImV4cCI6MjA4ODMxNDE0NH0.HFieHk3RFFeDhfV_aQeSsqTDFa-f7nuOv6_W0KTlO3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});